### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by yocchan-git** [yocchan-git/zero-steps#1]
DB設計をして、提出物を出す

**Comment by yocchan-git** [comment]
### ER図
お手数ですが、拡大してみていただけますと嬉しいです🙏
[![Image from Gyazo](https://i.gyazo.com/d980569aae31c4a53a7767b108b4221b.png)](https://gyazo.com/d980569aae31c4a53a7767b108b4221b)

### データ表
- usersテーブル

|id  |uid |name  |image |is_hidden |
|---|---|---|---|---|
|1  | 128437...|Aさん   | https://discord.ex.com/... | false|
|2  | 128438...|Bさん | https://discord.ex.com/... | false|
|3  | 128439...|株式会社のCさん  | https://discord.ex.com/... | true|

- goalsテーブル

|id  |user_id  |title |description |completed_at  |
|---|---|---|---|---|
|1  |1  |クロコダイルを倒す  |アラバスタで決戦 | 2024-03-25 17:08:37 +0900|
|2  |2  |サンジを救い出す |いざ、ビックマム | null|
|3  |3  |マッチョになる | ムキムキになって見返す(??) | null|

- tasksテーブル

|id  |user_id  |goal_id  |title  |completion_limits  |completed_at  |
|---|---|---|---|---|---|
|1  |1  |1  | ビビに出会う| 2024-03-24 17:08:37 +0900|2024-03-23 17:08:37 +0900|
|2  |1  |1  | アラバスタへ行く| 2024-03-24 17:08:37 +0900| 2024-03-25 17:08:37 +0900|
|3  |2  |2  | ホールケーキシャトーへ| 2024-03-24 17:08:37 +0900| null|
|4  |2  |2  | お茶会へ行く| 2024-03-24 17:08:37 +0900| null|
|5  |2  |2  | いざ、ミローワールド| 2024-03-24 17:08:37 +0900| null|
|6  |3  |3  | プロテインを買う| 2024-03-24 17:08:37 +0900| null|

- commentsテーブル

|id |user_id |content  |commentable_id  |commentable_type  |
|---|---|---|---|---|
|1 |1  |hogeです。ファイト！  |1  | Goal|
|2  |1  |hogeさん、ありがとうございます  |1  | Task|
|3  |3  |foobarです。アラバスタで会いましょう！  |2  | Task|

- complete_postsテーブル

|id |user_id  |complete_postable_id |complete_postable_type |content  |
|---|---|---|---|---|
|1 |1  |1 |Goal |目標を完了しました！  |
|2 |1  |1 |Task |タスクを完了しました！  |
|3 |1  |2 |Task |タスクを完了しました！  |

- relationshipsテーブル

|id |follower_id |following_id  |
|---|---|---|
|1 |1  |2  |
|2 |1  |3  |
|3 |2 |1  |

- notificationsテーブル

|id |user_id |content  | comment_id|
|---|---|---|---|
|1 |1  |Bさんからコメントがありました  | 1|
|2 |2 |Aさんからメンションがありました！ | 2|
|3 |2 |株式会社のCさんからメンションがありました！ | 3|
- timelinesテーブル

|id |user_id |content | timelineable_id| timelineable_type|
|---|---|---|---|---|
|1 |1  |Aさんがクロコダイルを倒す目標を作成しました | 1| Goal|
|2 |1 |Aさんがビビに出会うタスクを作成しました  | 1| Task|
|3 |2 |Bさんからコメントがありました | 1| Comment|
|3 |1 |Aさんからさんがビビに出会うタスクを終了しました | 2| CompletePost|

- reactionsテーブル

|id |user_id |reactionable_id  |reactionable_type  |
|---|---|---|---|
|1 |1  |1  |Comment |
|2 |2  |2  |CompletePost |
|3 |2 |3  |CompletePost |

**Comment by maedana** [comment]
凄いおかしいところがあるとかではないですが、気になったこと書いておきます。

- companiesのpasswordが平文のように見えるのが気になります。
  - 生徒側はみんなDiscord使ってるので、Discordログインなのだと理解しました。企業の方は使っているとは限らないのでid/passwordログイン? Railsなのかどうかもわからないですけどdevise使わない想定?
- 細かいですがcommentable_typeに入るのはRails前提ならクラス名なので、UserとかCompanyになりそうかなと思います。
- is_completeはもしかするとcompleted_atのように日時でもいいかもなと思いました。すると期限に対して前倒しで出来たとかみたいな情報としても使えますし。

**Comment by yocchan-git** [comment]
maedanaさん、ご確認いただきありがとうございます！
修正して、質問にはコメントしましたので確認いただけますと嬉しいです🙏

> 企業の方は使っているとは限らないのでid/passwordログイン?

おっしゃる通りで、企業の方がDiscordを使っているかわからないので別のログインです。
> Railsなのかどうかもわからないですけどdevise使わない想定?

はい！おっしゃる通りでdevise使わない想定です😆

> is_completeはもしかするとcompleted_atのように日時でもいいかもなと思いました。すると期限に対して前倒しで出来たとかみたいな情報としても使えますし。

なるほど！そういう視点はなかったので参考になります🙇‍♂️

### 修正箇所です
[![Image from Gyazo](https://i.gyazo.com/bb6260620cdad469c1603f14406f62db.png)](https://gyazo.com/bb6260620cdad469c1603f14406f62db)

- companies

|id  |name  |email |password_digest |industry |description |home_page_url | reset_digest| reset_sent_at|
|---|---|---|---|---|---|---|---|---|
|1  |株式会社E  |test_d@example.com  | ia26a$%w...|建築 | セカイヲカエル|https://hoge.example| ia49m$%w...| 2024-03-26|
|2  |株式会社F  |test_e@example.com | oaw6a$%w...|IT |セカイヲカエル| https://foobar.example| iow$%w...| 2024-03-26|

- tasksテーブル

|id  |user_id  |goal_id  |title  |completion_limits  |completed_at  |
|---|---|---|---|---|---|
|1  |1  |1  | ビビに出会う| 2024-03-24|2024-03-23|
|2  |1  |1  | アラバスタへ行く| 2024-03-24| null|
|3  |2  |2  | ホールケーキシャトーへ| 2024-03-24| null|
|4  |2  |2  | お茶会へ行く| 2024-03-24| null|
|5  |2  |2  | いざ、ミローワールド| 2024-03-24| null|
|6  |3  |3  | プロテインを買う| 2024-03-24| null|

- goal_commentsテーブル

|id |goal_id |content  |commentable_id  |commentable_type  |
|---|---|---|---|---|
|1 |1  |hogeです。ファイト！  |1  | Company|
|2  |1  |hogeさん、ありがとうございます  |3  | User|
|3  |3  |foobarです。ジムで会いましょう！  |2  | Company|

- task_commentsテーブル

|id |task_id |content  |commentable_id  |commentable_type  |
|---|---|---|---|---|
|1 |1  |hogeです。ファイト！  |1  | Company|
|2  |1  |hogeさん、ありがとうございます  |3  | User|
|3  |3  |foobarです。ジムで会いましょう！  |2  | Company|

**Comment by maedana** [comment]
> completed_at

時刻データ扱わないなら`completed_on`が適切かもですね。

> はい！おっしゃる通りでdevise使わない想定です😆

認証系gemを何を使わずに自前実装想定ですか? やってみること自体は凄くいいと思う一方で、もし自前実装だとするなら本番運用するにあたっては色々と気を使わないとセキュリティホールが生まれるリスクがある気もしますね。

**Comment by maedana** [comment]
設計としてはこれで基本いいとおもいます :+1:

**Comment by maedana** [comment]
見ましたー。

timelines/notificationsでペーパープロトの「詳しく見る」にあたる部分がURLに入るのだと思いましたがあってますかね? あってるとして、対象となるデータとの紐付けがないのは少し引っかかりますね。これがないとDB的に辿れないので分析とかするときに困るケースはあるかもしれないですね。あとはあんまりないとは思いますが、URL構造変えたくなったり、ドメイン変わったりするケースがあると、DBに入ってるURLの一括変換みたいなことが必要になるのかも、と思いました。

実際に何か困ることがあったらデータ移行頑張るとかでもいいですし、これで一旦進めてみるのでもいいかなと思います。

**Comment by yocchan-git** [comment]
> timelines/notificationsでペーパープロトの「詳しく見る」にあたる部分がURLに入るのだと思いましたがあってますかね? 

おっしゃる通りです。あってます！😊
> 対象となるデータとの紐付けがないのは少し引っかかりますね。

確かにです！承知しました。🙏
タイムライン・通知ともに関連付けをつけさせていただきます

指摘いただき、ありがとうございました！
またぜひ気になる点はコメントいただけますと嬉しいです🙇‍♂️

### 修正があったDB設計の箇所
- notificationsテーブル

|id |user_id |content  |url | comment_id|
|---|---|---|---|---|
|1 |1  |Bさんからコメントがありました  | https://…| 1|
|2 |2 |Aさんからメンションがありました！  |https://…| 2|
|3 |2 |株式会社のCさんからメンションがありました！  |https://…| 3|
- timelinesテーブル

|id |user_id |content  |url | timelineable_id| timelineable_type|
|---|---|---|---|---|---|
|1 |1  |Aさんがクロコダイルを倒す目標を作成しました  | https://…| 1| Goal|
|2 |1 |Aさんがビビに出会うタスクを作成しました  |https://…| 1| Task|
|3 |2 |Bさんからコメントがありました  |https://…| 1| Comment|
|3 |1 |Aさんからさんがビビに出会うタスクを終了しました  |https://…| 2| CompletePost|

**Comment by maedana** [comment]
タイムライン、通知にDBとの紐付けが出来たことでURLはDBになくとも関連から構築出来るものになったのではないですかね? 繰り返しですが、URL構造やドメインの変更等があるとDBのURLをどうするのか、という問題があるのでなくせるならURLはなくしたほうがシンプルになるのではないかな、と思います。なくせない理由があるなら残してもいいと思います。いかがですかね?

**Comment by yocchan-git** [comment]
> タイムライン、通知にDBとの紐付けが出来たことでURLはDBになくとも関連から構築出来るものになったのではないですかね?

こちら抜かしてました...おっしゃる通りurlなくてもいけそうです
指摘ありがとうございます！🙇‍♂️
> URL構造やドメインの変更等があるとDBのURLをどうするのか、という問題

こちらもありがとうございます！これで解消できそうです😁

### 修正があったDB設計の箇所

- notificationsテーブル

|id |user_id |content  | comment_id|
|---|---|---|---|
|1 |1  |Bさんからコメントがありました  | 1|
|2 |2 |Aさんからメンションがありました！ | 2|
|3 |2 |株式会社のCさんからメンションがありました！ | 3|
- timelinesテーブル

|id |user_id |content | timelineable_id| timelineable_type|
|---|---|---|---|---|
|1 |1  |Aさんがクロコダイルを倒す目標を作成しました | 1| Goal|
|2 |1 |Aさんがビビに出会うタスクを作成しました  | 1| Task|
|3 |2 |Bさんからコメントがありました | 1| Comment|
|3 |1 |Aさんからさんがビビに出会うタスクを終了しました | 2| CompletePost|
