### ISSUE TITLE
リソース設計をする

### ISSUE THREAD

**Issue by yocchan-git** [yocchan-git/zero-steps#27]
リソース設計をする

**Comment by yocchan-git** [comment]
リソース設計のバックアップ

リソース設計です！お手隙でご確認よろしくお願いいたします🙇‍♂️

|Method  |Path  |Description  |
|---|---|---|
|GET  |/users/sign_up  |ユーザーのサインアップ画面(Discord) |
|DELETE |/users/sign_out|ログアウトする |
|GET  |/auth/discord  |Discordでログイン後のリダイレクト先(ここでAPIを叩いてTOPへ遷移する)  |
|GET  |/users  |ユーザーの一覧を表示する  |
|GET  |/users/:user_id  |ユーザーの詳細を表示する  |
|POST  |/users/:user_id/follows  |対象ユーザーをフォローする  |
|DELETE  |/users/:user_id/follows/:follow_id  |対象ユーザーのフォローを解除する |
|GET  |/goals  |目標の一覧を表示する  |
|GET  |/goals/:goal_id  |目標の詳細を表示する  |
|GET  |/goals/new  |目標の詳細を表示する  |
|GET  |/goals/:goal_id/edit  |目標の編集画面を表示する  |
|POST  |/goals  |目標を追加する  |
|PATCH  |/goals/:goal_id |目標を更新する  |
|DELETE  |/goals/:goal_id  |目標を削除する  |
|GET  |/goals/:goal_id/comments  |目標のコメントの一覧を表示する  |
|POST  |/goals/:goal_id/comments  |目標のコメントを追加する  |
|DELETE  |/goals/:goal_id/comments/:comment_id  |目標のコメントを削除する |
|GET  |/goals/complete_posts/new  |目標の完了投稿作成画面  |
|POST  |/goals/complete_posts  |目標の完了投稿を追加する  |
|GET  |/goals/:goal_id/tasks  |タスクの一覧を表示する  |
|GET  |/goals/:goal_id/tasks/:task_id  |タスクの詳細を表示する  |
|GET  |/goals/:goal_id/tasks/new  |タスクの新規作成画面を表示する  |
|POST  |/goals/:goal_id/tasks  |タスクを作成する(Hotwireを使って非同期)  |
|PATCH  |/goals/:goal_id/tasks/:task_id  |タスクを更新する(Hotwireを使って非同期)   |
|DELETE  |/goals/:goal_id/tasks/:task_id  |タスクを削除する(Hotwireを使って非同期)   |
|GET  |/tasks/:task_id/comments  |タスクのコメントの一覧を表示する  |
|POST  |/tasks/:task_id/comments  |タスクのコメントを追加する  |
|DELETE  |/tasks/:task_id/comments/:comment_id  |タスクのコメントを削除する |
|GET  |/tasks/complete_posts/new  |タスクの完了投稿作成画面  |
|POST  |/tasks/complete_posts  |タスクの完了投稿を追加する  |
|GET  |/timelines  |タイムラインの一覧(TOP)を表示する  |
|POST  |/comments/:comment_id/reactions  |コメントにリアクションを追加する  |
|DELETE  |/comments/:comment_id/reactions /:reaction_id  |コメントのリアクションを削除する |
|POST  |/complete_posts/:complete_post_id/reactions  |終了投稿にリアクションを追加する  |
|DELETE  |/complete_posts/:complete_post_id/reactions /:reaction_id  |終了投稿のリアクションを削除する |

**Comment by maedana** [comment]
見ました。以下フィードバックです。

> /api/goals/:goal_id/tasks

互換性のない別バージョンを作りたくなったときに困るかも? よくやるのは/api/v1/... みたいにバージョンをつけるようにしたりします。このままでももし新しいのが欲しくなったら別URL作ればいいだけではありますが。

> POST	/companies/sign_in	ログイン処理を実装

凄く細かいのですが「実装」というワードが入ってるのは変かなと。

> DELETE	/sign_out	ログアウトする

/companies/sign_in と対になるようなURIがいいんじゃないかと思いました。

### その他
- 企業ログインはパスワードリセット機能が必要な気がしますけど、メールアドレスがないのでやりようがないですね。ペーパープロトでメールについては悩んでたような気がしますが。可能なら企業側もdiscordログインに倒せると色々シンプルになりそうだな、とは思いました。

**Comment by yocchan-git** [comment]
> 互換性のない別バージョンを作りたくなったときに困る

なるほど！そういう理由の`v1`なのですね🙏

> /companies/sign_in と対になるようなURIがいいんじゃないかと思いました。

こちら、ユーザーと企業の両方のログインを意図していました！言葉足らずで申し訳ございません
また、同じロジックになりそうですが問題ありましたらぜひ教えていただけますと🙇‍♂️

> 企業ログインはパスワードリセット機能が必要な気がします

あ〜完全に抜けてました😅

まず、Discordについて確認したのですがログインする企業さんはDiscordアカウントを持っていない方が多いらしく...
おっしゃる通りシンプルになるので、したいのは山々なのですがという感じです

となるとメールを持たせるようにしますね！
車輪の再発明になりますが、まぁ練習と思って実装します🙇‍♂️

### 修正した箇所です
|Method  |Path  |Description  |
|---|---|---|
|POST  |/api/v1/goals/:goal_id/tasks  |タスクを追加する(非同期)  |
|PATCH  |/api/v1/goals/:goal_id/tasks/:task_id  |タスクを更新する(非同期)   |
|DELETE  |/api/v1/goals/:goal_id/tasks/:task_id  |タスクを削除する(非同期)   |
|POST  |/companies/sign_in  |企業のログイン  |
|GET  |/companies/password/new  |企業のパスワード再設定メール送信画面 |
|POST  |/companies/password  |パスワード再設定のメール送信をする |
|GET  |/companies/password/edit  |パスワード再設定の画面 |
|PATCH  |/companies/password  |パスワード再設定をする |
|DELETE |/sign_out|ログアウトする(ユーザーと企業両方) |

**Comment by maedana** [comment]
確認しましたー、いいと思います :+1: 

> まず、Discordについて確認したのですがログインする企業さんはDiscordアカウントを持っていない方が多いらしく...
おっしゃる通りシンプルになるので、したいのは山々なのですがという感じです

なるほどー、やっぱりそういうことなのですね。このシステムを使いたいならDiscordアカウント取得してね、ぐらいにしてもいい気もしますが、そのへんはコーチの方?等とも要相談という感じでしょうかね。

**Comment by yocchan-git** [comment]
そうですね！相談してみます！
また機会があればよろしくお願い致します🙇‍♂️

**Comment by maedana** [comment]
再レビューしました。これといって気になるところはなかったです。
